### ISSUE TITLE
Collaborative VSCode

### ISSUE THREAD

**Issue by SimonBiggs** [ACPSEM/thursday#3]
Before tomorrow's meeting, could everyone download VS Code:

https://code.visualstudio.com/

And then install the live-share extension, logging in with your GitHub account:

https://code.visualstudio.com/learn/collaboration/live-share

**Comment by SimonBiggs** [comment]
@pchlap @Matthew-Jennings @quinn1234 @rnfinnegan @mitch-1211

**Comment by Matthew-Jennings** [comment]
Done :)
