### ISSUE TITLE
Meeting times in the new year

### ISSUE THREAD

**Issue by SimonBiggs** [ACPSEM/thursday#4]
Our last meetings for the year have been scheduled for the 9th and the 16th of December. With the 23rd and the 30th being skipped.

Michael from SA previously requested that we move the meeting time from 8 am to 8:30 am, but he's now no longer able to be a part of the group. Would everyone be okay with us taking two weeks off (skipping the 23rd and the 30th of December) and then starting back up on the 6th of Jan at 8 am NSW time?

**Comment by mitch-1211** [comment]
Sounds good to me @SimonBiggs

**Comment by Matthew-Jennings** [comment]
Settled on having first 2022 meeting on Jan 20th. Meetings start times are now 9:00 am NSW time.
