### ISSUE TITLE
Two repos

### ISSUE THREAD

**Issue by SimonBiggs** [ACPSEM/thursday#6]
What if we had two repos?

One repo which was as absolutely simple as possible, but it still included a few basics such as a single end-to-end automated test and a static analysis tool. That would be the "start here", everyone should be able to achieve this, and almost every project even research projects, would benefit from at least one automated end-to-end test and the usage of static analysis.

Then have a second repo which includes all of the bells and whistles.

Both of the repos are solving the same problem. But one repo is designed to be as accessible as achievable by those new to git, the other presents what should be aimed for.

**Comment by Matthew-Jennings** [comment]
Okay to close after today's meeting?

**Comment by SimonBiggs** [comment]
> Okay to close after today's meeting?

Yup :)
